package com.group13.studysync.data;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * The entity class representing a single Task in the database.
 * This defines the 'task_table' structure for Room.
 */
@Entity(tableName = "task_table")
public class Task {
    @PrimaryKey(autoGenerate = true)
    private int id; // Have a unique ID for each task (which is auto-generated by Room)
    private String title;
    private String description;
    private String dueDate;
    private String priority;
    private boolean isComplete;

    // Constructor for creating a new Task.
    public Task(String title, String description, String dueDate, String priority, boolean isComplete) {
        this.title = title;
        this.description = description;
        this.dueDate = dueDate;
        this.priority = priority;
        this.isComplete = isComplete;
    }

    // GETTERS AND SETTERS
    // (These allow Room and the UI to safely access the private variables)
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public boolean isComplete() {
        return isComplete;
    }

    public void setComplete(boolean complete) {
        isComplete = complete;
    }
}